# Generated by Django 2.1 on 2018-08-18 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=15)),
                ('lastname', models.CharField(max_length=16)),
                ('age', models.IntegerField(default=0)),
                ('BirthDate', models.DateTimeField()),
            ],
        ),
    ]
