# Generated by Django 2.1 on 2018-08-18 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('haliloia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StudentDegree', models.IntegerField(default=0)),
                ('StudentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='haliloia.Student')),
            ],
        ),
    ]
