# Generated by Django 2.1 on 2018-08-18 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haliloia', '0002_degree'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_aces', models.CharField(max_length=1000)),
                ('mission', models.CharField(max_length=1000)),
                ('vision', models.CharField(max_length=1000)),
                ('youtube_link', models.CharField(max_length=1000)),
                ('accepted', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='degree',
            name='StudentID',
        ),
        migrations.DeleteModel(
            name='Degree',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
